require File.dirname(__FILE__) + '/geoservices/base'
require File.dirname(__FILE__) + '/geoservices/layerable'
require File.dirname(__FILE__) + '/geoservices/queryable'
require File.dirname(__FILE__) + '/geoservices/service/catalog'
require File.dirname(__FILE__) + '/geoservices/service/feature_service'
require File.dirname(__FILE__) + '/geoservices/service/map_service'
